# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

before_script:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

script: coverage run --source flockcontext setup.py test

after_success:
  - pip install coveralls
  - coveralls
